name: Testing NPM Caching
on: workflow_dispatch

jobs:
    node-build-cache:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3

            - name: Build Project
              run: npm install
            
            - name: Test Project
              run: npm test